version: '3.8'
services:
  game-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "game"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin-game-db:
    container_name: pgadmin4_container_game
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: phoekoby@mail.ru
      PGADMIN_DEFAULT_PASSWORD: phoekoby
    ports:
      - "5050:80"